# Generated by Django 4.1.3 on 2023-01-18 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0002_destination_student_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
