# Generated by Django 4.1.3 on 2023-01-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0006_alter_student_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('HOD', 'Head of Department')], default='', max_length=50),
        ),
    ]
