# Generated by Django 4.1.3 on 2023-01-20 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0007_complaint_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='role',
        ),
    ]
