# Generated by Django 4.1.3 on 2023-01-21 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0009_student_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='cc.student'),
            preserve_default=False,
        ),
    ]
