# Generated by Django 4.1.3 on 2023-01-22 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0016_alter_complaint_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(default='')),
                ('comp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cc.complaint')),
            ],
        ),
    ]
