# Generated by Django 4.1.3 on 2023-01-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0017_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('PN', 'Pending'), ('SO', 'Solved'), ('RJ', 'Rejected')], default='PN', max_length=2),
        ),
    ]
