# Generated by Django 4.1.3 on 2023-02-19 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0020_alter_complaint_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compbranch', to='cc.branch'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compcategory', to='cc.category'),
        ),
    ]
