# Generated by Django 4.1.3 on 2023-02-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0022_alter_branch_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='c_date',
            field=models.DateField(auto_now=True),
        ),
    ]
